# GitHub Actions workflow to deploy infrastructure using OpenTofu
# This workflow automatically deploys infrastructure changes when files in the infrastructure/ directory are modified

name: Deploy Infrastructure

# Trigger on pushes to the master branch when files in the infrastructure/ directory change
on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'

# Environment variables used throughout the workflow
env:
  TOFU_VERSION: '1.6.0'  # Specify the OpenTofu version to use
  AWS_PAGER: ""  # Disable AWS CLI pagination
  CERTIFICATE_VALIDATION_TIMEOUT: "1800"  # 30 minutes timeout for certificate validation

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opentofu/opentofu:1.6.0  # Using OpenTofu container directly
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_PAGER: ""
    
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Set up AWS profile for OpenTofu
      - name: Set up AWS profile
        run: |
          mkdir -p ~/.aws
          echo "[dollar-game]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[dollar-game]" > ~/.aws/config
          echo "region=us-east-1" >> ~/.aws/config
      
      # Step 3: Initialize OpenTofu
      - name: Initialize OpenTofu
        working-directory: ./infrastructure
        run: tofu init
      
      # Step 4: Plan infrastructure changes
      - name: Plan infrastructure changes
        working-directory: ./infrastructure
        run: tofu plan -out=tfplan
      
      # Step 5: Apply infrastructure changes
      - name: Apply OpenTofu
        working-directory: ./infrastructure
        run: tofu apply tfplan
        
      # Step 6: Output the deployment status
      - name: Deployment Status
        working-directory: ./infrastructure
        run: |
          echo "Infrastructure deployment completed"
          echo "S3 Website URL (internal only):"
          tofu output s3_website_url
